### ISSUE TITLE
小程序在详情页是裁剪后的图

### ISSUE THREAD

**Issue by cijianzy** [www-chao-fun/chaofun-wechat-light-app#24]
![image](https://user-images.githubusercontent.com/6985160/140605018-75dad883-44ca-46d1-a95f-238cb916b8ce.png)

**Comment by jlin-z** [comment]
这个是什么意思啊

**Comment by jlin-z** [comment]
你放了个这个图上来有点上头啊

**Comment by cijianzy** [comment]
@jlin-z  就是图片不是原图，有点模糊，这个问题好像已经修了，可以先不看，我确认后再开启吧，谢谢：）
